version: '3'
services:
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "8080:8080"
    depends_on:
      - server